version: '3.7'

services:
  app:
    build:
      context: .
    container_name: user-app
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    networks:
      - user-app-api

  postgres:
    image: kartoza/postgis:latest
    container_name: user-app-db
    restart: unless-stopped
    ports:
      - ${DB_HOST_PORT}:5432
    networks:
      - user-app-api
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # networks:
    #   - local-user-app

networks:
  user-app-api:

volumes:
  postgres-data:
