version: '3.8'

services:
  app:
    container_name: user-app-api
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    image: kartoza/postgis:latest
    container_name: user-app-db
    restart: unless-stopped
    ports:
      - ${DB_HOST_PORT}:5432
    networks:
      - nesjs-network
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_app
    volumes:
      - .:/usr/postgresql/data

networks:
  nesjs-network:
